"""Initial migration - create all tables

Revision ID: 1906749dda03
Revises: 
Create Date: 2025-12-01 15:01:08.624449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1906749dda03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('operation_type', sa.String(length=100), nullable=True),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_transactions_created', 'credit_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_transactions_created_at'), 'credit_transactions', ['created_at'], unique=False)
    op.create_index('ix_credit_transactions_entity', 'credit_transactions', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_entity_id'), 'credit_transactions', ['entity_id'], unique=False)
    op.create_index('ix_credit_transactions_entity_product', 'credit_transactions', ['entity_type', 'entity_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_entity_type'), 'credit_transactions', ['entity_type'], unique=False)
    op.create_index(op.f('ix_credit_transactions_product_id'), 'credit_transactions', ['product_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tier_id', sa.String(length=50), nullable=False),
    sa.Column('pricing_type', sa.String(length=20), nullable=False),
    sa.Column('pricing_config', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_plan_id'), 'subscription_plans', ['plan_id'], unique=True)
    op.create_index(op.f('ix_subscription_plans_product_id'), 'subscription_plans', ['product_id'], unique=False)
    op.create_index('ix_subscription_plans_product_tier', 'subscription_plans', ['product_id', 'tier_id'], unique=False)
    op.create_table('usage_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('current_usage', sa.Integer(), nullable=False),
    sa.Column('reset_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('current_usage >= 0', name='ck_current_usage_positive'),
    sa.CheckConstraint('limit_value >= 0', name='ck_limit_value_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_limits_entity', 'usage_limits', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_usage_limits_entity_id'), 'usage_limits', ['entity_id'], unique=False)
    op.create_index('ix_usage_limits_entity_product_period', 'usage_limits', ['entity_type', 'entity_id', 'product_id', 'period'], unique=True)
    op.create_index(op.f('ix_usage_limits_entity_type'), 'usage_limits', ['entity_type'], unique=False)
    op.create_index(op.f('ix_usage_limits_product_id'), 'usage_limits', ['product_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('tier_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_action'), 'usage_records', ['action'], unique=False)
    op.create_index('ix_usage_records_created', 'usage_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_records_created_at'), 'usage_records', ['created_at'], unique=False)
    op.create_index('ix_usage_records_entity', 'usage_records', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_usage_records_entity_id'), 'usage_records', ['entity_id'], unique=False)
    op.create_index('ix_usage_records_entity_product', 'usage_records', ['entity_type', 'entity_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_usage_records_entity_type'), 'usage_records', ['entity_type'], unique=False)
    op.create_index(op.f('ix_usage_records_product_id'), 'usage_records', ['product_id'], unique=False)
    op.create_table('credit_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('subscription_credits', sa.Integer(), nullable=False),
    sa.Column('purchased_credits', sa.Integer(), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=True),
    sa.Column('is_credits_enabled', sa.Boolean(), nullable=False),
    sa.Column('credits_reset_at', sa.DateTime(), nullable=True),
    sa.Column('next_reset_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('purchased_credits >= 0', name='ck_purchased_credits_positive'),
    sa.CheckConstraint('subscription_credits >= 0', name='ck_subscription_credits_positive'),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_wallets_entity', 'credit_wallets', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_credit_wallets_entity_id'), 'credit_wallets', ['entity_id'], unique=False)
    op.create_index('ix_credit_wallets_entity_product', 'credit_wallets', ['entity_type', 'entity_id', 'product_id'], unique=True)
    op.create_index(op.f('ix_credit_wallets_entity_type'), 'credit_wallets', ['entity_type'], unique=False)
    op.create_index(op.f('ix_credit_wallets_product_id'), 'credit_wallets', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_wallets_product_id'), table_name='credit_wallets')
    op.drop_index(op.f('ix_credit_wallets_entity_type'), table_name='credit_wallets')
    op.drop_index('ix_credit_wallets_entity_product', table_name='credit_wallets')
    op.drop_index(op.f('ix_credit_wallets_entity_id'), table_name='credit_wallets')
    op.drop_index('ix_credit_wallets_entity', table_name='credit_wallets')
    op.drop_table('credit_wallets')
    op.drop_index(op.f('ix_usage_records_product_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_entity_type'), table_name='usage_records')
    op.drop_index('ix_usage_records_entity_product', table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_entity_id'), table_name='usage_records')
    op.drop_index('ix_usage_records_entity', table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_created_at'), table_name='usage_records')
    op.drop_index('ix_usage_records_created', table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_action'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_usage_limits_product_id'), table_name='usage_limits')
    op.drop_index(op.f('ix_usage_limits_entity_type'), table_name='usage_limits')
    op.drop_index('ix_usage_limits_entity_product_period', table_name='usage_limits')
    op.drop_index(op.f('ix_usage_limits_entity_id'), table_name='usage_limits')
    op.drop_index('ix_usage_limits_entity', table_name='usage_limits')
    op.drop_table('usage_limits')
    op.drop_index('ix_subscription_plans_product_tier', table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_product_id'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_plan_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_credit_transactions_product_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_entity_type'), table_name='credit_transactions')
    op.drop_index('ix_credit_transactions_entity_product', table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_entity_id'), table_name='credit_transactions')
    op.drop_index('ix_credit_transactions_entity', table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_created_at'), table_name='credit_transactions')
    op.drop_index('ix_credit_transactions_created', table_name='credit_transactions')
    op.drop_table('credit_transactions')
    # ### end Alembic commands ###
